### ISSUE TITLE
Why use 3D editor to develop 2D games?

### ISSUE THREAD

**Issue by ForeverPx** [oussamabonnor1/ChasingPlanes_Unity3D#2]
Why use 3D editor to develop 2D games?

**Comment by oussamabonnor1** [comment]
Unity is designed to handle 3D/2D/VR...etc

For example, the famous game [CupHead](https://en.wikipedia.org/wiki/Cuphead) was made in Unity which was a 2D game.

They talk about 2D in their webstie as well https://unity.com/solutions/2d

Hope that helps!
